## Numpy Array and Basics
Learning about numpy

In [2]:
import numpy as np

In [3]:
array_1d = np.array([1,2,3,4,5])

In [4]:
print(array_1d)

[1 2 3 4 5]


In [5]:
# array_2d = np.array([1,2,3],[4,5,6]) # This will give error
# print(array_2d)

In [6]:
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


### LIST VS NUMPY ARRAY

In [7]:

py_list = [1,2,3]
print("Python list multiplication ",py_list*2)
py_array = np.array([1,2,3])
print("Python list multiplication ",py_array*2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python list multiplication  [2 4 6]


#### _Numpy Arrays just work like matrices_

In [8]:
import time
start_time = time.time()
py_list = [i*2 for i in range(100000000)]
print("\nList Operation time: ",time.time()-start_time)

start_time = time.time()
np_array = np.arange(100000000) * 2
print("\nArray Operation time: ",time.time()-start_time)



List Operation time:  5.317627668380737

Array Operation time:  0.2114245891571045


### Creating Arrays From Scratch

In [9]:
print(zeros:=np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
print(zeros:=np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
print(full:=np.full((2,2),7))

[[7 7]
 [7 7]]


In [12]:
print(random := np.random.random((4,7)))

[[0.40598578 0.42904714 0.33172281 0.74117231 0.87619175 0.37842308
  0.92887309]
 [0.86422289 0.99167158 0.32146614 0.52304978 0.00777098 0.18247845
  0.82801114]
 [0.85887483 0.01123727 0.97806583 0.34427569 0.64802853 0.51929077
  0.73851326]
 [0.41761215 0.64753269 0.06877088 0.49261381 0.41276248 0.19026971
  0.05405585]]


Random Values Flutuate between 0 and 1

In [13]:
print(sequence := np.arange(0,10,2))

[0 2 4 6 8]


### Vector | Tensor | Matrices

In [14]:
print(vector := np.array([1,2,3,4,5,6]))

print(matrix := np.array([[1,2,3,4],[1,2,3,4],[3,4,5,6]]))

print(tensor := np.array([[[1,2,3,4,1,2],[1,2,3,4,2,1]],[[5,6,7,8,9,10],[1,2,3,4,5,6]]]))

[1 2 3 4 5 6]
[[1 2 3 4]
 [1 2 3 4]
 [3 4 5 6]]
[[[ 1  2  3  4  1  2]
  [ 1  2  3  4  2  1]]

 [[ 5  6  7  8  9 10]
  [ 1  2  3  4  5  6]]]


### Array Properties

In [15]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
print("Shape :: ",arr.shape)
print("N Dimentions :: ",arr.ndim)
print("Size ie No of elements:: ",arr.size)
print("Datatype :: ",arr.dtype)

Shape ::  (2, 4)
N Dimentions ::  2
Size ie No of elements::  8
Datatype ::  int64


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original Array :: ",arr)

reshaped = arr.reshape((3,4))
print("Reshaped Array :: ",reshaped)

flattened = reshaped.flatten()
print("Flattened Array :: ",flattened)

raveled = reshaped.ravel()
print("Raveled Array :: ",raveled)

transpose = reshaped.T


Original Array ::  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array ::  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array ::  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array ::  [ 0  1  2  3  4  5  6  7  8  9 10 11]
