# Numpy Array Operations

In [1]:
import numpy as np

In [2]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print("Negetive Indexing :: ",arr[-3])
print("Basic Slicing :: ",arr[2:7])
print("With Step :: ",arr[2:7:2]) # every second position

Negetive Indexing ::  7
Basic Slicing ::  [2 3 4 5 6]
With Step ::  [2 4 6]


In [3]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific Element :: ",arr_2d[1,2]) # arr[row,column]
print("Row 1 :: ",arr_2d[1]) # 2nd row
print("Column 0 :: ",arr_2d[:,0]) # 1st column

Specific Element ::  6
Row 1 ::  [4 5 6]
Column 0 ::  [1 4 7]


## Sorting

In [4]:
unsorted = np.array([2,2,3,3,74,23,754,312,54254235,25236])
print("Sorted Array :: ",np.sort(unsorted))

array_2d_unsorted = np.array([[1,32,13],
                              [14,11,19],
                              [3,2,1]])
print("2d Sorted array column wise :: ",np.sort(array_2d_unsorted,0)) # mostly used
print("2d Sorted array row wise :: ",np.sort(array_2d_unsorted,1))

Sorted Array ::  [       2        2        3        3       23       74      312      754
    25236 54254235]
2d Sorted array column wise ::  [[ 1  2  1]
 [ 3 11 13]
 [14 32 19]]
2d Sorted array row wise ::  [[ 1 13 32]
 [11 14 19]
 [ 1  2  3]]


## Fitering

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,0])
print("Even Numbers :: ",even_numbers := numbers[numbers%2==0])

Even Numbers ::  [2 4 6 8 0]


## Filters with Masks

In [6]:
mask = numbers > 5
mask_even = numbers % 2 == 0
print("Numbers > 5 :: ",numbers[mask])
print("Even Numbers :: ",numbers[mask_even])

Numbers > 5 ::  [6 7 8 9]
Even Numbers ::  [2 4 6 8 0]


## Fancy Indexing vs np.where()

In [7]:
indices = [0,2,4,9]
print(numbers[indices]) # This will return the values at indexs 0 2 4 and 9

where_numbers = np.where(numbers > 5)
print("NP values where numbers are greater than 5 :: ",numbers[where_numbers])

[1 3 5 0]
NP values where numbers are greater than 5 ::  [6 7 8 9]


In [8]:
print(conditional_array := np.where(numbers>4,numbers*2,numbers))

# conditional_array = numbers*2 agar number 4 se bada hai toh and numbers agar nahi hai toh


[ 1  2  3  4 10 12 14 16 18  0]


In [9]:
print(conditional_array := np.where(numbers>4,"true","false"))
# iska matlab hai ki pahli 4 values false hongi baki true

['false' 'false' 'false' 'false' 'true' 'true' 'true' 'true' 'true'
 'false']


## Adding and Removing Data 

In [10]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print("Sum :: ",arr_sum := arr1 + arr2)
print("Concatination :: ",arr_full := np.concatenate((arr1,arr2))) # arr_full := np.concatenate((arr1,arr2))

Sum ::  [ 6  8 10 12]
Concatination ::  [1 2 3 4 5 6 7 8]


## Array Concatablity

In [11]:
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4])
c = np.array([5,6,7,8,9,0])

print("Compatibility Shapes a b :: ",a.shape==b.shape)
print("Compatibility Shapes a c :: ",a.shape==c.shape)
print("Compatibility Shapes b c :: ",b.shape==c.shape)

Compatibility Shapes a b ::  False
Compatibility Shapes a c ::  True
Compatibility Shapes b c ::  False


In [12]:
print(original := np.array(
  [
    [1,2],
    [3,4]
  ]
  ))

new_row = np.array([[5,6]])
print()
print(with_new_row := np.vstack((original,new_row)))

print()
new_column = np.array([[3],[5]])
print(with_new_column := np.hstack((original,new_column)))


[[1 2]
 [3 4]]

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [3 4 5]]


In [13]:
arr = np.array([i for i in range(1,40)])
print("Array after deletion :: ",deleted := np.delete(arr,2),"\n\n")

arr_large = np.array([i for i in range(1,40)])
print("Array after deletion with \nstart: number>10\nstep 2 \n\nStop: number<30:: ",deleted := np.delete(arr_large,[i for i in range(10,30,2)]))

Array after deletion ::  [ 1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39] 


Array after deletion with 
start: number>10
step 2 

Stop: number<30::  [ 1  2  3  4  5  6  7  8  9 10 12 14 16 18 20 22 24 26 28 30 31 32 33 34
 35 36 37 38 39]
