## Numpy Array and Basics
Learning about numpy

In [20]:
import numpy as np

In [21]:
array_1d = np.array([1,2,3,4,5])

In [22]:
print(array_1d)

[1 2 3 4 5]


In [23]:
# array_2d = np.array([1,2,3],[4,5,6]) # This will give error
# print(array_2d)

In [24]:
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


### LIST VS NUMPY ARRAY

In [25]:

py_list = [1,2,3]
print("Python list multiplication ",py_list*2)
py_array = np.array([1,2,3])
print("Python list multiplication ",py_array*2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python list multiplication  [2 4 6]


#### _Numpy Arrays just work like matrices_

In [26]:
import time
start_time = time.time()
py_list = [i*2 for i in range(100000000)]
print("\nList Operation time: ",time.time()-start_time)

start_time = time.time()
np_array = np.arange(100000000) * 2
print("\nArray Operation time: ",time.time()-start_time)



List Operation time:  5.2316765785217285

Array Operation time:  0.23978495597839355


### Creating Arrays From Scratch

In [27]:
print(zeros:=np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
print(zeros:=np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [29]:
print(full:=np.full((2,2),7))

[[7 7]
 [7 7]]


In [30]:
print(random := np.random.random((4,7)))

[[0.26480145 0.62072475 0.13525234 0.06135554 0.56934383 0.73421336
  0.56900954]
 [0.37664887 0.53999139 0.69507326 0.4083517  0.21362871 0.26020521
  0.36437199]
 [0.62932275 0.63380005 0.48505383 0.97770871 0.70471229 0.34300467
  0.9979001 ]
 [0.18428518 0.48283787 0.88705429 0.17635137 0.61050779 0.2976626
  0.95190589]]


Random Values Flutuate between 0 and 1

In [31]:
print(sequence := np.arange(0,10,2))

[0 2 4 6 8]


### Vector | Tensor | Matrices

In [36]:
print(vector := np.array([1,2,3,4,5,6]))

print(matrix := np.array([[1,2,3,4],[1,2,3,4],[3,4,5,6]]))

print(tensor := np.array([[[1,2,3,4,1,2],[1,2,3,4,2,1]],[[5,6,7,8,9,10],[1,2,3,4,5,6]]]))

[1 2 3 4 5 6]
[[1 2 3 4]
 [1 2 3 4]
 [3 4 5 6]]
[[[ 1  2  3  4  1  2]
  [ 1  2  3  4  2  1]]

 [[ 5  6  7  8  9 10]
  [ 1  2  3  4  5  6]]]


### Array Properties

In [ ]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
print("Shape :: ",arr.shape)
print("N Dimentions :: ",arr.ndim)
print("Size ie No of elements:: ",arr.size)
print("Datatype :: ",arr.dtype)